### ISSUE TITLE
Can you support a picture click preview?

### ISSUE THREAD

**Issue by jjjachyty** [meteorlxy/vue-showdown#1]

**Comment by meteorlxy** [comment]
Could you please provide details about this feature?

**Comment by jjjachyty** [comment]
i use this for display my articles,the articles has imges,i want to preview when i click article's images

**Comment by meteorlxy** [comment]
@jjjachyty 

You can try with [medium-zoom](https://github.com/francoischalifour/medium-zoom).

FIY, there is an [example](https://github.com/vuejs/vuepress/blob/master/packages/%40vuepress/plugin-medium-zoom/mixin.js) that how Vuepress integrate `medium-zoom` with Vue.

I'll close this issue as this is not related to `showdown` and `vue-showdown`.
