### ISSUE TITLE
Nuxt / TypeScript support

### ISSUE THREAD

**Issue by webcoderkz** [meteorlxy/vue-showdown#11]
Does it work with above topics?

**Comment by meteorlxy** [comment]
- Nuxt: Yes, vue-showdown is simply a Vue component
- Typescript: Yes, we have provided types defs in `types` folder

**Comment by webcoderkz** [comment]
Can you throw an example, on how to use this with Nuxt? Would it have SSR? Because you're saying it's just a component.
