### ISSUE TITLE
style of vue-showdown not show with vue template

### ISSUE THREAD

**Issue by Navyroot** [meteorlxy/vue-showdown#13]
### index.js
```js
import Vue from 'vue';
import App from './App.vue';

Vue.config.productionTip = false;
import VueShowdown from 'vue-showdown'

// the second parameter of Vue.use() is optional
Vue.use(VueShowdown, {
  // set default flavor of showdown
  flavor: 'github',
  // set default options of showdown (will override the flavor options)
  options: {
    emoji: false,
  },
})

new Vue({
  render: h => h(App),
}).$mount('#app');

```
#### Vue template code : 
```js
<template>
  <div>
    <vue-showdown :markdown="fileContent"></vue-showdown> 
  </div>
</template>
<script>
import fileMd from 'raw-loader!../README.md'
export default {
  name: 'app',
  data() {
    return {
      fileContent: '## __Hello__',
    }
  },
  mounted() {
    this.fileContent = fileMd
  },
}
</script>
```

## Markdown script : 
![Screen Shot 2019-12-18 at 8 03 03 AM](https://user-images.githubusercontent.com/31533986/71047265-ad3f9a80-216d-11ea-8644-283deb56fc4b.png)

## Result of my test page: 
![Screen Shot 2019-12-18 at 8 02 16 AM](https://user-images.githubusercontent.com/31533986/71047301-cf391d00-216d-11ea-9823-8f992a3eb40f.png)

## Result demo page : 
![Screen Shot 2019-12-18 at 7 59 56 AM](https://user-images.githubusercontent.com/31533986/71047356-f7c11700-216d-11ea-9bba-3bd0ce01b882.png)

**Comment by meteorlxy** [comment]
The markdown style does not come with `vue-showdown` nor `showdown`. You need to import it yourself.

Try [github-markdown-css](https://www.npmjs.com/package/github-markdown-css)

**Comment by Navyroot** [comment]
Thank , it's work .

**Comment by Navyroot** [comment]
How about syntax highlight ?

**Comment by meteorlxy** [comment]
It's out of scope of this vue component.

You can try something like highlight.js

**Comment by Navyroot** [comment]
Yes,thank I will try 😃

**Comment by Aycayilmz** [comment]
I have the same problem, how did you find a solution?
