### ISSUE TITLE
Support for Vue 3

### ISSUE THREAD

**Issue by yuideveloper** [meteorlxy/vue-showdown#23]
Hello,

I attempted to add Vue Showdown into a Vue 3 app following the steps shown [here](https://vue-showdown.js.org/#easy-to-use). Unfortunately, the component does need seem to render. Is Vue Showdown compatible with Vue 3? Is the a JSFiddle or otherwise that proves this out?

Thank you.

**Comment by meteorlxy** [comment]
The guide is for Vue2.

For Vue3, you have to `const app = createApp()` and `app.use()` ...

(Not tested, but it might work)

I'll find time to deal with it

**Comment by yuideveloper** [comment]
Thank you for your willingness to look into this. If this helps, I currently receive the following:

```
Component is missing template or render function.
``

**Comment by BedfordWest** [comment]
I'm getting this even in Vue2 despite following the instructions in the README and on the website. Specifically:

```
vue.runtime.esm.js?2b0e:619 [Vue warn]: Failed to mount component: template or render function not defined.

found in

---> <VueShowdown>
       <Description> at src/components/Description.vue
         <Pane>
           <Splitpanes>
             <Pane>
               <Splitpanes>
                 <Day> at src/components/Day.vue
                   <App> at src/App.vue
                     <Root>
```

**Comment by chaozbj** [comment]
Got same error, please help to fix

**Comment by meteorlxy** [comment]
Busy developing VuePress 2 these days. I'll upgrade this lib soon

**Comment by meteorlxy** [comment]
v3.0.0 is released :tada:

Let me know if you meet any problems.
