### ISSUE TITLE
options not working

### ISSUE THREAD

**Issue by blairun** [meteorlxy/vue-showdown#25]
I'm having trouble making the options work. I've also tried loading showdown as a plugin (rather than component) with the same result. For example, the code below doesn't render the emoji as I would expect. 

I'm using 
    "vue": "2.6.12",
    "vue-showdown": "2.4.1",

```html
<template>
  <div>
    <VueShowdown
      markdown="**Testing 123**  :smile"
      :options="{ emoji: true }"
    />
  </div>
</template>
<script>
import { VueShowdown } from 'vue-showdown'
export default {
  components: {
    VueShowdown,
  }
</script>
```

renders as:
**Testing 123** :smile

**Comment by meteorlxy** [comment]
Looks like you've missed the ending `:` ? i.e.

`:smile` -> `:smile:`

**Comment by meteorlxy** [comment]
Closing as this looks stale.
