### ISSUE TITLE
How do you use this with nuxt?

### ISSUE THREAD

**Issue by rublev** [meteorlxy/vue-showdown#26]
I've tried the following:

**plugins/showdown.js**

```javascript
import Vue from 'vue'
import { VueShowdownPlugin } from 'vue-showdown'

Vue.component('vue-showdown', VueShowdownPlugin)
```

I've also tried:

```
Vue.use(VueShowdownPlugin, {
  options: {
    emoji: true,
  },
})
```

which results in a `Cannot read property 'install' of undefined` error.

**nuxt.config.js**

```javascript
plugins: [
  { src: '~/plugins/showdown.js', mode: 'client' },
],
```

**component**

```
<VueShowdown markdown="`vue-showdown` is easy to use :kissing_heart:" />
```

And I get this error:

![image](https://user-images.githubusercontent.com/470273/106064739-51617800-60c8-11eb-97eb-729222e7a366.png)

**Comment by meteorlxy** [comment]
Current latest version is for vue 3 only. You should check out the v2 branch.

```sh
npm i vue-showdown@2
```

https://github.com/meteorlxy/vue-showdown/tree/v2

**Comment by rublev** [comment]
> Current latest version is for vue 3 only. You should check out the [v2 branch](https://github.com/meteorlxy/vue-showdown/tree/v2).
> 
> ```shell
> npm i vue-showdown@2
> ```

I was using 2.4.1 in the OP.

**Comment by meteorlxy** [comment]
I'll add a notice in the documentation

**Comment by meteorlxy** [comment]
Well, I closed this issue because your original post is invalid usage.

For v3:

```js
import { createApp } from 'vue';
import { VueShowdownPlugin } from 'vue-showdown';
```

For v2:

```js
import Vue from 'vue'
import VueShowdown from 'vue-showdown'
```

What you did:

```js
import Vue from 'vue'
import { VueShowdownPlugin } from 'vue-showdown'
```

**Comment by rublev** [comment]
Yes thank you I know what I did, none of these combinations work. Were you able to actually get either v2 or v3 working with Nuxt? Either way I just ripped it out from the source and it works fine now since it's impossible to use with Nuxt successfully.

Thanks for the library.

**Comment by ddahan** [comment]
For those taking a look to this issue, using Nuxt 3, you have absolutely nothing to do to make it work.
Just install the plugin with npm, and there in the component: `import { VueShowdown } from "vue-showdown";`
It's surprisingly easy.
