### ISSUE TITLE
Version 3.0.0 is not on NPM?

### ISSUE THREAD

**Issue by rosen91** [meteorlxy/vue-showdown#27]
Trying to install this on a Vue 3 app, but noticed that the latest version is not published on NPM? Is there any reason for this?
[https://www.npmjs.com/package/vue-showdown](https://www.npmjs.com/package/vue-showdown)

**Comment by meteorlxy** [comment]
Weird. I must have published it before 🤔

**Comment by rosen91** [comment]
That's a fast response if i ever seen one :) Does this mean that it will get published today?

**Comment by meteorlxy** [comment]
Just published it. Maybe I forgot to do that? 🤔 

Anyway, thanks for reporting.
