### ISSUE TITLE
how to use extension "showdown-katex" with options

### ISSUE THREAD

**Issue by jackywu** [meteorlxy/vue-showdown#28]
thanks for your great work.
I'm going to use extension  [showdown-katex](https://github.com/obedm503/showdown-katex)，and want put some options to this extension，after read [your document](https://vue-showdown.js.org/guide/#extensions) and [showdown-katex document](https://github.com/obedm503/showdown-katex) but still did not find a way to do it. could you tell some suggestion?

**Comment by meteorlxy** [comment]
```js
import 'showdown-katex';
```

```vue
<VueShowdown:extensions="['showdown-katex']" />
```

It works here
