### ISSUE TITLE
Options: Tables misaligned with character  ` 

### ISSUE THREAD

**Issue by belueg** [meteorlxy/vue-showdown#39]
## Bug report

When I set the option for tables as `true`, there are some cases where  if appears the character `   tables get misaligned. 
Below I share some screenshots to make the issue understandable.

### Description

The tables normally work nice! But if in the table appears the character ` as a value, the tables get misaligned.  

### Steps to reproduce

- You can use the README of this repo to reproduce it https://github.com/cycloid-community-catalog/infra-amazon-elk/tree/master
- The Terraform table has the values `subnet_ids` and `vpc_id` that have the values `` as default. So when you use vue-showdown to parse this README the problem appears

- Reproduction link / repo:

The repo is private, but I can share with you this piece of code that we use to parse the markdown :) 

```js
   <vue-showdown
              v-if="!_.isEmpty(readme)"
              flavor="github"
              :options="{ tables: true }"
              class="markdown__file"
              :markdown="$sanitizeHtml(readme)"/>
```

### Expected behavior

The ideal behavior would be that the tables don't get misaligned 

#### Screenshot from GitHub README 
![image](https://user-images.githubusercontent.com/44982655/160099596-83bdc1d1-0e49-4ef7-910c-110df7195047.png)

#### Screenshot when markdown is parsed
![image](https://user-images.githubusercontent.com/44982655/160099568-82b07f08-08b9-488a-9788-c270971074a1.png)

### Environment info

- `vue-showdown` version: 2.4.1
- `showdown` version: - 
- `vue` version: 2.6.14
- Browser: Chrome

**Comment by meteorlxy** [comment]
As a personal suggestion about your docs, you can consider using `` `''` `` instead of ``` `` ``` if the default value is an empty string.

**Comment by meteorlxy** [comment]
Closing as it's an issue of showdown.js
