### ISSUE TITLE
[Feature request] Add types declaration for Typescript users

### ISSUE THREAD

**Issue by ddahan** [meteorlxy/vue-showdown#47]
### Clear and concise description of the problem

There is no type declaration associated with the project, creating a Typescript error after:

```ts
import { VueShowdown } from "vue-showdown";
```

<img width="488" alt="image" src="https://github.com/meteorlxy/vue-showdown/assets/1933516/7f3365b5-d08f-4366-a72f-7e74616fa4e0">

### Suggested solution

When a user types `npm install --save-dev @types/vue-showdown` it should install types with it.

**Comment by meteorlxy** [comment]
Um, I think the "types" fields at the root of `package.json` should work in a previous typescript version. Which version of TS were you using?

**Comment by meteorlxy** [comment]
Alright, the "types" field at the root of `package.json` won't be used as the fallback types. I think I misunderstood it before.
