### ISSUE TITLE
is it possible to parse vue components in markup?

### ISSUE THREAD

**Issue by Worie** [meteorlxy/vue-showdown#5]
Hi, quick question: I'm working on an app where content can be "dynamically loaded" and I wanted to allow users to use regular markup, alongside with other vue components. For example:

```
# some heading  
`something else`
<some-component />
blah blah blah
``` 

I don't really mind the syntax, but I just want to use vue-components between text in markup.

is it possible in `vue-showdown`? Or perhaps you have some hints how could I achieve something similar? Thanks!

**Comment by meteorlxy** [comment]
That's an interestring feature, and it's possible in `vue-showdown` with some modifications:

- Use the __Runtime + Compiler__ build of Vue, as we need to compile templates on the client.
- Treat the HTML string that generated by showdown as Vue template:

Current:
https://github.com/meteorlxy/vue-showdown/blob/0f78edea5c83a3d731fcff9647530feb98db6969/src/components/vue-showdown.js#L123-L129

Modified:
```js
  render (h) {
    return h({
      template: `<${this.tag}>${this.outputHtml}</${this.tag}>`,
    })
  },
```

**Comment by meteorlxy** [comment]
This feature is supported since v2.4.0. 

See [docs about `vueTemplate` prop](https://vue-showdown.js.org/guide/#vuetemplate)
