### ISSUE TITLE
样式怎么不对？

### ISSUE THREAD

**Issue by ichrislu** [meteorlxy/vue-showdown#6]
对不起，我是vue初学者。
我把vue-showdown加入到vue中后，成功解析了md内容，但样式很丑~~以为是样式污染，我建了一个干净的项目，什么样式都没有，只引用了vue-showdown，模仿 https://vue-showdown.js.org/playground/ 的功能，是最简单的代码。但解析出来的效果仍然不如官方 https://vue-showdown.js.org/playground/ 出来的效果好，请问，我是少了什么吗？比如样式？

非常感谢

**Comment by meteorlxy** [comment]
你需要自己给页面加上markdown的样式，不然使用的是浏览器的默认样式。

你现在看到的那些支持markdown的平台其实都是有自己的样式的，比如现在github这里也是。

有一个叫 github-markdown-css 的项目提取了 github 使用的 md 样式，可以直接拿来用。

**Comment by ichrislu** [comment]
谢谢，已搞定
试了一下，感觉样式还是不如playground的好，方便共享一下css吗？

**Comment by rememple** [comment]
> 谢谢，已搞定
> 试了一下，感觉样式还是不如playground的好，方便共享一下css吗？

你好，我也是个初学者，我查了半天也没搞明白如何添加样式，请问可以指导一下吗？谢谢！！！
