### ISSUE TITLE
Can't install extension over vue plugin.

### ISSUE THREAD

**Issue by juangnakarani** [meteorlxy/vue-showdown#9]
I want to use [showdown-highlight](https://www.npmjs.com/package/showdown-highlight), an extension  showdown for syntax highlighting. VueShowdown installed as vue plugin. There is no issue but the extension is not working. I was checking all dependency related extension and there is no issue. Here is my code snippet:

``` javascript
  //main.js
  import ShowdownHighlight from 'showdown-highlight/lib'

  Vue.use(VueShowdown, {
  // set default flavor of showdown
  flavor: 'github',
  // set default options of showdown (will override the flavor options)
  options: {
    emoji: true,
  },
  extensions: [ShowdownHighlight]
})
```
and
``` javascript
  //Component.vue
  <VueShowdown :markdown="fileContent"/>
```
based on the following [documentation](https://vue-showdown.js.org/guide/#extensions), extension installed as object or array.

**Comment by meteorlxy** [comment]
Based on our current documentation:

![image](https://user-images.githubusercontent.com/18205362/58214624-0acf4e00-7d29-11e9-83e2-756277f74d59.png)

![image](https://user-images.githubusercontent.com/18205362/58214604-f25f3380-7d28-11e9-9f4e-471b0d97b864.png)
